version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: gratstats-mysql
    env_file: ../.env
    ports:
      - "3306:3306"
    volumes:
      - ../database/mysql-data:/var/lib/mysql
      - ../database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
